language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
# - name: LanguageModelFeaturizer
#   model_name: "bert"
#   model_weights: "rasa/LaBSE"
- name: DIETClassifier
  epochs: 100
  learning_rate: 0.001
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20230608-080205-hushed-graph
